// pronto derivation: reads and handler lists from screen markup.
//
// A screen's markup already says which collections it reads (`data-live`,
// `data-reads`) and which Jessie modules it binds (`data-handler`,
// `data-on-*`); restating both in program.cue was two statements of one fact.
// This pass projects them out of the markup into program_derived.cue, which unifies
// into the program — so `cue export` stays the one source the emitter and the
// checkers read, and the markup is the authority.
//
// Derived per screen: `reads` as the SET of entities the markup touches
// (sorted, deduped, no filter/order/select — those live in the markup alone),
// and `files.handlers` as shell/handlers/<name>.js for every handler name.
// Screen names come from shell/screens/*.html; a stale html file for a screen
// the program no longer declares fails the export rather than deriving in
// silence.

type Entity = { table: string; path: string };

const TAG = /<[a-z][a-z0-9]*\s[^>]*>/gi;
const STYLE = /<style\b[^>]*>[\s\S]*?<\/style>/gi;
const ATTR = /\s(data-[a-z][a-z-]*)="([^"]*)"/g;

const decode = (v: string) =>
  v.replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"').replace(/&#39;/g, "'");

/** Tables read and handler modules bound by one screen's markup. */
export function scanScreen(html: string): { tables: string[]; handlers: string[] } {
  const tables = new Set<string>();
  const handlers = new Set<string>();
  for (const tag of html.replace(STYLE, "").matchAll(TAG)) {
    for (const [, name, raw] of tag[0].matchAll(ATTR)) {
      const value = decode(raw);
      if (name === "data-live") tables.add(value);
      else if (name === "data-reads") {
        for (const t of value.split(",")) if (t.trim() !== "") tables.add(t.trim());
      } else if (name === "data-handler" || name.startsWith("data-on-")) handlers.add(value);
    }
  }
  return { tables: [...tables].sort(), handlers: [...handlers].sort() };
}

const quoteKey = (k: string) => (/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(k) ? k : `"${k}"`);

export function renderDerived(
  pkg: string,
  screens: { name: string; entities: string[]; handlers: string[] }[],
): string {
  const blocks = screens.map(({ name, entities, handlers }) => {
    const reads = entities.map((e) => `{entity: "${e}"}`).join(", ");
    const mods = handlers.map((h) => `"shell/handlers/${h}.js"`).join(", ");
    return `\t${quoteKey(name)}: {\n\t\treads: [${reads}]\n\t\tfiles: handlers: [${mods}]\n\t}`;
  });
  return `// generated by pronto from screen markup — do not edit\npackage ${pkg}\n\ncode: surface: screens: {\n${
    blocks.join("\n")
  }\n}\n`;
}

function fail(msg: string): never {
  console.error(`pronto derive: ${msg}`);
  Deno.exit(1);
}

/** Scan the app's screens and write program_derived.cue beside program.cue. */
export async function derive(appDir: string): Promise<void> {
  const program = await Deno.readTextFile(`${appDir}/program.cue`);
  const pkg = /^package (\w+)$/m.exec(program)?.[1] ?? fail(`${appDir}/program.cue names no package`);

  const exported = await new Deno.Command("cue", {
    args: ["export", ".", "-e", "code.state.entities", "--out", "json"],
    cwd: appDir,
    stdout: "piped",
    stderr: "inherit",
  }).output();
  if (!exported.success) fail("cue export of code.state.entities failed");
  const entities: Record<string, Entity> = JSON.parse(new TextDecoder().decode(exported.stdout));
  const byTable = new Map(Object.entries(entities).map(([name, e]) => [e.table, name]));

  const screens: { name: string; entities: string[]; handlers: string[] }[] = [];
  for await (const f of Deno.readDir(`${appDir}/shell/screens`)) {
    if (!f.isFile || !f.name.endsWith(".html")) continue;
    const name = f.name.slice(0, -".html".length);
    const { tables, handlers } = scanScreen(await Deno.readTextFile(`${appDir}/shell/screens/${f.name}`));
    const named = tables.map((t) =>
      byTable.get(t) ?? fail(`${name}.html reads "${t}", the table of no declared entity`)
    );
    screens.push({ name, entities: [...new Set(named)].sort(), handlers });
  }
  screens.sort((a, b) => (a.name < b.name ? -1 : 1));
  await Deno.writeTextFile(`${appDir}/program_derived.cue`, renderDerived(pkg, screens));
}
