// The CEL derivation: one `cel:` string per constraint, and everything the
// rest of the program needs said in its own language, rendered from the
// parsed expression.
//
// Two artifacts, both checked in, both generated:
//
//   .pronto/cel.json   cel.expr.ParsedExpr per distinct constraint, canonical
//                      protobuf-JSON, one line per constraint so a changed
//                      constraint is a changed line.
//   program_cel.cue    the CHECK bodies and CUE constraints, whose own header
//                      states what each block is for.

import type { ParsedExpr } from "./cel-emit.ts";
import { cueConstraint, sqlCheck } from "./cel-emit.ts";

export type Entity = {
  table: string;
  path: string;
  fields: { name: string; cel?: string }[];
  invariant?: { cel: string };
};

/** Where a constraint is stated. `col` is the column a field-level `this`
 * stands for, or null for an entity's row-level invariant. */
export type CelSite = { entity: string; path: string; col: string | null; cel: string };

const BROWSER = new Set(["tab", "device"]);

/** Every constraint a program states, in declaration order. */
export function celSites(entities: Record<string, Entity>): CelSite[] {
  const sites: CelSite[] = [];
  for (const [entity, e] of Object.entries(entities)) {
    for (const f of e.fields ?? []) {
      if (f.cel !== undefined) sites.push({ entity, path: e.path, col: f.name, cel: f.cel });
    }
    if (e.invariant !== undefined) sites.push({ entity, path: e.path, col: null, cel: e.invariant.cel });
  }
  return sites;
}

/** .pronto/cel.json: the IR of every distinct constraint, keyed by source. */
export function renderIr(irs: Map<string, ParsedExpr>): string {
  const lines = [...irs.keys()].sort().map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(irs.get(k))}`);
  return `{\n${lines.join(",\n")}\n}\n`;
}

import { quoteKey } from "./cue.ts";

/** program_cel.cue, or the reason a constraint has no rendering. */
export function renderCel(pkg: string, sites: CelSite[], irs: Map<string, ParsedExpr>): string {
  const ir = (cel: string) => irs.get(cel) ?? (() => { throw new Error(`no IR for ${JSON.stringify(cel)}`); })();
  // The CHECK body is the one rendering with no "no rendering" answer: a
  // server-tier field whose constraint reaches no SQL is a constraint the
  // database does not hold, and it must stop the derivation naming itself.
  const sql = (s: CelSite) => {
    try {
      return sqlCheck(ir(s.cel), s.col);
    } catch (e) {
      throw new Error(`${s.entity}.${s.col ?? "<invariant>"}: cel ${JSON.stringify(s.cel)} has no SQL: ${(e as Error).message}`);
    }
  };
  const blocks: string[] = [];
  let usesStrings = false;
  for (const entity of [...new Set(sites.map((s) => s.entity))]) {
    const mine = sites.filter((s) => s.entity === entity);
    const lines: string[] = [];
    // A browser tier emits no table, so a CHECK body would render nowhere.
    const checks = BROWSER.has(mine[0].path)
      ? []
      : mine.filter((s) => s.col !== null).map((s) => `\t\t${quoteKey(s.col!)}: ${JSON.stringify(sql(s))}`);
    if (checks.length > 0) lines.push(`\tchecks: {\n${checks.join("\n")}\n\t}`);
    const invariant = mine.find((s) => s.col === null);
    if (invariant !== undefined && !BROWSER.has(invariant.path)) {
      lines.push(`\tinvariant: check: ${JSON.stringify(sql(invariant))}`);
    }
    const seed: string[] = [];
    for (const s of mine) {
      if (s.col === null) continue;
      const c = cueConstraint(ir(s.cel), true);
      if ("no" in c) {
        lines.push(`\t// ${s.col} states no CUE constraint: ${c.no}`);
        continue;
      }
      if (c.strings) usesStrings = true;
      seed.push(`\t\t${quoteKey(s.col)}?: ${c.cue}`);
    }
    if (seed.length > 0) lines.push(`\tseed: [...{\n${seed.join("\n")}\n\t}]`);
    if (lines.length > 0) blocks.push(`${quoteKey(entity)}: {\n${lines.join("\n")}\n}`);
  }
  const body = blocks.map((b) => b.split("\n").map((l) => `\t${l}`).join("\n")).join("\n");
  return [
    "// generated by pronto from the cel: constraints in program.cue — do not edit",
    "//",
    "// `checks` are the SQL CHECK bodies emit.cue renders into the table DDL;",
    "// `seed` carries what each field-level cel says about the field's own",
    "// value, which is what vets a stated row. An invariant binds `this` to the",
    "// ROW, and a predicate over several columns constrains no single field's",
    "// value, so it derives a CHECK body and nothing for CUE.",
    `package ${pkg}`,
    "",
    ...(usesStrings ? ['import "strings"', ""] : []),
    "code: state: entities: {",
    body,
    "}",
    "",
  ].join("\n");
}
