// pronto writer: materializes a program's emission bundle onto disk.
//
//   deno run --allow-read=apps/todo --allow-write=apps/todo --allow-run=cue \
//     plugins/pronto/write.ts apps/todo
//
// CUE stays pure; all IO lives here (the bayt generate.nu division of labor).
// Structured entries (`data`) serialize to YAML; raw entries (`text`) are
// written verbatim with a provenance header; `src` entries are assembly files
// authored in place — verified present, copied only when target ≠ src, never
// headed. Files recorded in the previous run's .pronto/manifest.json but
// absent from the current bundle are removed, so renamed targets leave no
// stale emissions.

import { stringify } from "jsr:@std/yaml@1.0.5";
import { derive } from "./derive.ts";

type EmitFile = { format: string; text?: string; data?: unknown; src?: string };
type Bundle = { manifest: string[]; files: Record<string, EmitFile> };

// jessie/bloblang/js entries always carry `src`, never `text`, so they need
// no header; a `text:` entry in one of them is meant to fail render()'s
// unknown-format check and force a header decision.
const HEADER: Record<string, string> = {
  sql: "-- generated by pronto from program.cue — do not edit\n",
  yaml: "# generated by pronto from program.cue — do not edit\n",
  caddyfile: "# generated by pronto from program.cue — do not edit\n",
  cue: "// generated by pronto from program.cue — do not edit\n",
  css: "/* generated by pronto from program.cue — do not edit */\n",
  html: "<!-- generated by pronto from program.cue — do not edit -->\n",
  text: "",
};

function fail(msg: string): never {
  console.error(`pronto write: ${msg}`);
  Deno.exit(1);
}

const appDir = Deno.args[0] ?? fail("usage: write.ts <appDir>  (runs `cue export` in appDir — needs --allow-run=cue)");

function render(rel: string, f: EmitFile): string {
  if (f.format === "json") return JSON.stringify(f.data, null, 2) + "\n"; // no comment syntax, no header
  const header = HEADER[f.format] ?? fail(`${rel}: unknown format ${f.format}`);
  if (f.text !== undefined) return header + f.text;
  if (f.format === "yaml") return header + stringify(f.data, { lineWidth: -1 });
  return fail(`${rel}: no text and format ${f.format} is not structured`);
}

async function exportBundle(): Promise<Bundle> {
  const exported = await new Deno.Command("cue", {
    args: ["export", ".", "-e", "out", "--out", "json"],
    cwd: appDir,
    stdout: "piped",
    stderr: "inherit",
  }).output();
  if (!exported.success) fail("cue export failed");
  const bundle: Bundle = JSON.parse(new TextDecoder().decode(exported.stdout));
  const keys = Object.keys(bundle.files).sort();
  const manifest = [...bundle.manifest].sort();
  if (JSON.stringify(keys) !== JSON.stringify(manifest)) {
    fail(`manifest and files disagree:\n  manifest: ${manifest}\n  files: ${keys}`);
  }
  // bayt resolves a project from the `apps/<meta.name>` its export names, and
  // meta.name is the emitted package name too, so it can carry no hyphen. The
  // scan that would catch a mismatch runs over the build graph with no app in
  // hand to name, which is why this is checked here instead.
  const dir = (bundle.files["bayt.json"]?.data as { dir?: string } | undefined)?.dir;
  if (dir !== undefined) {
    const here = Deno.realPathSync(appDir);
    if (here !== dir && !here.endsWith(`/${dir}`)) {
      fail(
        `bayt.json names dir "${dir}" but this app is at "${here}": a project's ` +
          `dir is apps/<meta.name>, so the directory's own name must be meta.name`,
      );
    }
  }
  return bundle;
}

async function writeBundle(bundle: Bundle): Promise<void> {
  const manifest = [...bundle.manifest].sort();
  for (const rel of manifest) {
    if (rel.startsWith("/") || rel.split("/").includes("..")) fail(`unsafe path: ${rel}`);
    const f = bundle.files[rel];
    const path = `${appDir}/${rel}`;
    const dir = path.slice(0, path.lastIndexOf("/"));
    if (f.src !== undefined) {
      if (f.text !== undefined || f.data !== undefined) fail(`${rel}: src is exclusive with text/data`);
      if (f.src.startsWith("/") || f.src.split("/").includes("..")) fail(`unsafe src: ${f.src}`);
      let stat;
      try {
        stat = await Deno.stat(`${appDir}/${f.src}`);
      } catch {
        fail(`${rel}: missing assembly source ${f.src}`);
      }
      if (!stat.isFile) fail(`${rel}: assembly source ${f.src} is not a file`);
      if (f.src !== rel) {
        if (dir !== appDir) await Deno.mkdir(dir, { recursive: true });
        await Deno.writeTextFile(path, await Deno.readTextFile(`${appDir}/${f.src}`));
      }
      continue;
    }
    if (dir !== appDir) await Deno.mkdir(dir, { recursive: true });
    await Deno.writeTextFile(path, render(rel, f));
  }

  const manifestPath = `${appDir}/.pronto/manifest.json`;
  let previous: string[] = [];
  try {
    previous = JSON.parse(await Deno.readTextFile(manifestPath));
  } catch (e) {
    if (!(e instanceof Deno.errors.NotFound)) throw e;
  }
  for (const rel of previous) {
    if (!bundle.files[rel]) await Deno.remove(`${appDir}/${rel}`).catch(() => {});
  }
  await Deno.mkdir(`${appDir}/.pronto`, { recursive: true });
  await Deno.writeTextFile(manifestPath, JSON.stringify(manifest, null, 2) + "\n");
}

const derivedText = () => Deno.readTextFile(`${appDir}/program_derived.cue`).catch(() => "");

// Markup-derived declarations regenerate before the export that reads them —
// and once more after the write, because a component screen's html is itself
// an OUTPUT of the export (#Screen.markup) while derive reads the emitted
// screens. A run that moved one re-derives and re-exports once; a derivation
// still moving after that is a bug, never a longer loop.
await derive(appDir);
let bundle = await exportBundle();
await writeBundle(bundle);
const settled = await derivedText();
await derive(appDir);
if ((await derivedText()) !== settled) {
  bundle = await exportBundle();
  await writeBundle(bundle);
  const again = await derivedText();
  await derive(appDir);
  if ((await derivedText()) !== again) fail("derivation did not settle in two passes");
}
console.error(`pronto write: ${bundle.manifest.length} files → ${appDir}`);
