// pronto writer: materializes a program's emission onto disk.
//
//   deno run --allow-read=apps/todo --allow-write=apps/todo --allow-run=cue \
//     plugins/pronto/write.ts apps/todo
//
// CUE stays pure; all IO lives here (the bayt generate.nu division of labor).
// Structured entries (`data`) serialize to YAML; raw entries (`text`) are
// written verbatim with a provenance header; `src` entries are assembly files
// authored in place — verified present, copied only when target ≠ src, never
// headed. .pronto/manifest.json records what the writer wrote, and a recorded
// file absent from the current emission is removed, so renamed targets leave no
// stale emissions; a file authored in place is never recorded, so the sweep
// cannot reach it.

import { stringify } from "jsr:@std/yaml@1.0.5";
import { derive, terminalPath } from "./derive.ts";
import { entries, exists, ifMissing } from "./missing.ts";
import { projectSay } from "./project-config.ts";
import { generateTypeSQL } from "./type-sql.ts";
import { generateProto, type ProtoEntity } from "./type-proto.ts";
import { checkTypeSeeds, type TypeEntity } from "./type-check.ts";
import { parseHeld, seedSql, type SeedData } from "./seed.ts";

type EmitFile = { format: string; text?: string; data?: unknown; src?: string };
type Emission = {
  manifest: string[];
  files: Record<string, EmitFile>;
  terminal: { surface: { runtime: string; documentRenderer: string; documentConfig: string } };
  build?: { meta?: { local?: boolean } };
  cluster?: { meta?: { root?: string; statics?: { file: string }[] } };
};

// jessie/bloblang/js entries always carry `src`, never `text`, so they need
// no header; a `text:` entry in one of them is meant to fail render()'s
// unknown-format check and force a header decision.
const HEADER: Record<string, string> = {
  sql: "-- generated by pronto from program.cue — do not edit\n",
  yaml: "# generated by pronto from program.cue — do not edit\n",
  caddyfile: "# generated by pronto from program.cue — do not edit\n",
  cue: "// generated by pronto from program.cue — do not edit\n",
  toml: "# generated by pronto from program.cue — do not edit\n",
  css: "/* generated by pronto from program.cue — do not edit */\n",
  html: "<!-- generated by pronto from program.cue — do not edit -->\n",
  document: "<!-- generated by pronto from program.cue — do not edit -->\n",
  text: "",
};

// A migration applies whole or not at all: one that fails part-way leaves a
// schema the steps after it cannot assume, and the two timeouts bound how long a
// single statement may hold a lock before it gives the database back. The
// transaction is also what lets an index be built plainly — CONCURRENTLY is
// wanted only outside one, and cannot run inside one.
//
// Emitted text only. `src` assembly files are copied verbatim further down, and
// wrapping SQL a person authored would change what they wrote.
const MIGRATION = /^services\/database\/migrations\/[^/]+\.sql$/;
const PROLOGUE = "SET lock_timeout = '5s';\nSET statement_timeout = '60s';\n\nBEGIN;\n\n";

function fail(msg: string): never {
  console.error(`pronto write: ${msg}`);
  Deno.exit(1);
}

/** SQL with its provenance header, wrapped where the file is a migration. */
function sqlFile(rel: string, body: string): string {
  if (!MIGRATION.test(rel)) return HEADER.sql + body;
  return HEADER.sql + PROLOGUE + body + (body.endsWith("\n") ? "" : "\n") + "\nCOMMIT;\n";
}

const appDir = Deno.args[0] ?? fail("usage: write.ts <appDir>  (runs `cue export` in appDir — needs --allow-run=cue)");

function render(rel: string, f: EmitFile): string {
  if (f.format === "type-sql" || f.format === "carrier-sql") return sqlFile(rel, generateTypeSQL(f.data as { precision: number; scale: number }[]));
  if (f.format === "seed-sql") {
    const data = f.data as SeedData;
    // Read, not judged: derive judged these bytes, and check-facts holds the
    // file to the hash it judged.
    const held = data.src === undefined ? {} : parseHeld(data.src, Deno.readTextFileSync(`${appDir}/${data.src}`));
    return sqlFile(rel, seedSql(data, held));
  }
  if (f.format === "proto") return generateProto(f.data as Record<string, ProtoEntity>);
  if (f.format === "json") return JSON.stringify(f.data, null, 2) + "\n"; // no comment syntax, no header
  const header = HEADER[f.format] ?? fail(`${rel}: unknown format ${f.format}`);
  if (f.text !== undefined) return f.format === "sql" ? sqlFile(rel, f.text) : header + f.text;
  if (f.format === "yaml") return header + stringify(f.data, { lineWidth: -1 });
  return fail(`${rel}: no text and format ${f.format} is not structured`);
}

async function exportEmission(): Promise<Emission> {
  const exported = await new Deno.Command("cue", {
    args: ["export", ".", "-e", "out", "--out", "json"],
    cwd: appDir,
    stdout: "piped",
    stderr: "inherit",
  }).output();
  if (!exported.success) fail("cue export failed");
  const emission: Emission = JSON.parse(new TextDecoder().decode(exported.stdout));
  checkTypeSeeds(emission.files["schema/entities.proto"].data as Record<string, TypeEntity>);
  emission.files[".say.yaml"].data = await projectSay(appDir, emission.files[".say.yaml"].data);
  const keys = Object.keys(emission.files).sort();
  const manifest = [...emission.manifest].sort();
  if (JSON.stringify(keys) !== JSON.stringify(manifest)) {
    fail(`manifest and files disagree:\n  manifest: ${manifest}\n  files: ${keys}`);
  }
  // The scan that would catch a mismatch runs over the build graph with no app
  // in hand to name, which is why this is checked here instead.
  const dir = (emission.files["bayt.json"]?.data as { dir?: string } | undefined)?.dir;
  if (dir !== undefined) {
    // Compared in the spelling a bayt.json holds, which is always
    // forward-slashed where realPathSync answers in the platform's own.
    const here = Deno.realPathSync(appDir).replaceAll("\\", "/");
    // "." is an installed pronto's app and "" the workspace root's own.
    if (dir !== "." && dir !== "" && here !== dir && !here.endsWith(`/${dir}`)) {
      fail(
        `bayt.json names dir "${dir}" but this app is at "${here}": the dir a ` +
          `project names must be the directory the app is in`,
      );
    }
  }
  // An installed loop with a monorepo cluster layout serves docker copies
  // that resolve nowhere: the cluster's statics stay workspace-relative
  // instead of the app's own files plus the terminal's image. The seats
  // below name the disagreement; SPEC's canonical program.cue shape derives
  // the layout from the terminal so the two cannot drift apart.
  if (emission.build?.meta?.local === false && emission.cluster?.meta?.root !== undefined && emission.cluster.meta.root !== "") {
    fail(
      `this app is installed (its loop names no pronto sources) but its cluster seat kept the monorepo layout (meta.root is ${JSON.stringify(emission.cluster.meta.root)}): ` +
        `make the seats agree — SPEC's canonical program.cue shape derives "local" from the terminal and hands "terminal" to the build seat`,
    );
  }
  // Every static the cluster serves from the build context is either an
  // emission output (written by this run: screens, manifests, documents)
  // or the app's own file: one naming a path nothing holds fails here, at
  // generate, rather than minutes later in a docker build.
  // Runtime-prefixed files (a `../` path the root context serves in the
  // monorepo) are the terminal's, not the app's, and are skipped.
  for (const s of emission.cluster?.meta?.statics ?? []) {
    if (s.file.startsWith("../")) continue;
    if (emission.files[s.file] !== undefined) continue;
    if ((await ifMissing(Deno.stat(`${appDir}/${s.file}`), null)) === null) {
      fail(`${s.file}: no such file — the cluster serves it from the build context, so it must exist in the app (most often the review ladder's brief.html, authored per SPEC's brief.html section)`);
    }
  }
  return emission;
}

const unsafe = (p: string) => p.split("/").some((s) => s === "" || s === "." || s === "..");
const parent = (p: string) => p.slice(0, p.lastIndexOf("/"));

const empty = async (dir: string) => (await entries(dir, null))?.length === 0;

/** The paths the last run recorded, vetted whole before any is acted on. */
async function recorded(manifestPath: string): Promise<string[]> {
  const text = await ifMissing(Deno.readTextFile(manifestPath), null);
  if (text === null) return [];
  let parsed: unknown;
  try {
    parsed = JSON.parse(text);
  } catch (e) {
    fail(`${manifestPath}: ${(e as Error).message}`);
  }
  const paths: unknown = (parsed as { written?: unknown } | null)?.written;
  if (!Array.isArray(paths) || paths.some((p) => typeof p !== "string" || unsafe(p))) {
    fail(`${manifestPath} is not {written: [...]} of paths inside the app: restore it, or delete it and sweep the last run's emissions by hand`);
  }
  return paths as string[];
}

/** Everything the run will write, rendered, so nothing on disk moves for an
 * emission the writer refuses. Documents are the one exception, rendered by
 * renderDocuments once the files they are rendered from are on disk. */
async function rendered(emission: Emission): Promise<Map<string, string>> {
  const contents = new Map<string, string>();
  for (const rel of [...emission.manifest].sort()) {
    if (unsafe(rel)) fail(`unsafe path: ${rel}`);
    const f = emission.files[rel];
    if (f.format === "document") continue;
    if (f.src === undefined) {
      contents.set(rel, render(rel, f));
      continue;
    }
    if (f.text !== undefined || f.data !== undefined) fail(`${rel}: src is exclusive with text/data`);
    if (unsafe(f.src)) fail(`unsafe src: ${f.src}`);
    const stat = await ifMissing(Deno.stat(`${appDir}/${f.src}`), null) ?? fail(`${rel}: missing assembly source ${f.src}`);
    if (!stat.isFile) fail(`${rel}: assembly source ${f.src} is not a file`);
    if (f.src !== rel) {
      contents.set(rel, await Deno.readTextFile(`${appDir}/${f.src}`));
      continue;
    }
    // A file the writer emitted cannot become the author's by being named in
    // place: its banner says whose it is.
    const header = HEADER[f.format];
    if (header && (await Deno.readTextFile(`${appDir}/${rel}`)).startsWith(header)) {
      fail(`${rel}: is a pronto emission, not an authored file: delete it and author it`);
    }
  }
  return contents;
}

/** The documents an emission lists, rendered by the terminal it names from the
 * served tree this run has just written: a document is the screen the shell
 * would draw first, which only the terminal can say. Spawned from the app's
 * own directory, as derive spawns the markup reader, and held to the list:
 * a document the terminal wrote that the program does not name, or the
 * reverse, is the two disagreeing about which addresses are prerendered. */
async function renderDocuments(emission: Emission): Promise<Map<string, string>> {
  const wanted = Object.keys(emission.files).filter((rel) => emission.files[rel].format === "document").sort();
  const contents = new Map<string, string>();
  if (wanted.length === 0) return contents;
  // Inside the app, the one tree this writer may write, and removed before it
  // returns.
  const out = await Deno.makeTempDir({ dir: `${appDir}/.pronto`, prefix: "documents-" });
  try {
    // An installed terminal names both from its own root, where mise put it.
    const surface = emission.terminal.surface;
    const named = { terminalRuntime: surface.runtime };
    const renderer = await terminalPath(named, surface.documentRenderer, appDir);
    const config = await terminalPath(named, surface.documentConfig, appDir);
    // One door serves them all, so one origin stands for it in every document.
    const spelled = wanted.map((rel) => emission.files[rel].data as { origin: string; declare: string });
    const { origin, declare } = spelled[0];
    if (spelled.some((d) => d.origin !== origin || d.declare !== declare)) fail("the documents name more than one origin");
    // Under the terminal's config and the lock beside it, frozen: what the
    // renderer writes is committed, so every package it reaches is the one the
    // lock names. The lock is named because deno would otherwise anchor it at
    // the workspace the config sits in.
    const run = await new Deno.Command("deno", {
      args: ["run", "--config", config, "--lock", config.replace(/deno\.json$/, "deno.lock"), "--frozen", "--no-check", "--allow-read=.", `--allow-write=${out}`, renderer, ".", out, origin],
      cwd: appDir,
      stdout: "inherit",
      stderr: "inherit",
    }).output();
    if (!run.success) fail(`${renderer} could not render this app's documents`);
    const found: string[] = [];
    const walk = async (dir: string, rel: string) => {
      for await (const e of Deno.readDir(dir)) {
        if (e.isDirectory) await walk(`${dir}/${e.name}`, `${rel}/${e.name}`);
        else found.push(`documents${rel}/${e.name}`);
      }
    };
    await walk(out, "");
    found.sort();
    if (JSON.stringify(found) !== JSON.stringify(wanted)) {
      fail(`the terminal rendered documents the program does not list, or missed some:\n  rendered: ${found}\n  listed: ${wanted}`);
    }
    for (const rel of wanted) {
      const html = await Deno.readTextFile(`${out}/${rel.slice("documents/".length)}`);
      // The door runs each as a template, which declares the origin and spells
      // it where the renderer was told to; any other `{{` in a reader's words
      // or a screen's markup is text, and is written as the template's own
      // literal of it.
      const text = html.split(origin).map((part) => part.replaceAll("{{", '{{"{{"}}')).join(origin);
      contents.set(rel, HEADER.document + declare + "\n" + text);
    }
    return contents;
  } finally {
    await Deno.remove(out, { recursive: true });
  }
}

/** Writes the emission and returns the paths it wrote. */
async function writeEmission(emission: Emission): Promise<string[]> {
  const contents = await rendered(emission);
  const documents = Object.keys(emission.files).filter((rel) => emission.files[rel].format === "document");
  const written = [...contents.keys(), ...documents].sort();
  const manifestPath = `${appDir}/.pronto/manifest.json`;
  // Swept before anything is written, so a rename never removes its own target
  // where the filesystem folds case; recorded before anything is written, so a
  // run that dies midway leaves nothing the next one cannot find.
  const stale: string[] = [];
  for (const rel of await recorded(manifestPath)) {
    if (emission.files[rel]) continue;
    const info = await ifMissing(Deno.lstat(`${appDir}/${rel}`), null);
    if (info === null) continue;
    if (info.isDirectory) fail(`${rel}: recorded as written, but is now a directory`);
    stale.push(`${appDir}/${rel}`);
  }
  for (const path of stale) {
    await Deno.remove(path);
    for (let dir = parent(path); dir !== appDir && await empty(dir); dir = parent(dir)) await Deno.remove(dir);
  }
  await Deno.mkdir(`${appDir}/.pronto`, { recursive: true });
  await Deno.writeTextFile(manifestPath, JSON.stringify({ written }, null, 2) + "\n");
  const put = async (rel: string, text: string) => {
    const path = `${appDir}/${rel}`;
    const dir = parent(path);
    if (dir !== appDir) await Deno.mkdir(dir, { recursive: true });
    await Deno.writeTextFile(path, text);
  };
  for (const [rel, text] of contents) await put(rel, text);
  for (const [rel, text] of await renderDocuments(emission)) await put(rel, text);
  return written;
}

const derivedText = () => ifMissing(Deno.readTextFile(`${appDir}/program_derived.cue`), "");

// A directory named from another, both forward-slashed and absolute.
function pathFrom(base: string, target: string): string {
  const here = base.split("/");
  const there = target.split("/");
  let shared = 0;
  while (shared < here.length && shared < there.length && here[shared] === there[shared]) shared++;
  return [...here.slice(shared).map(() => ".."), ...there.slice(shared)].join("/");
}

/** The layout this app is built in, stated for its program as omnishell's mode
 * states the terminal's: this pronto as the app names it, the app's directory
 * under its CUE module's root, and that root and the runtime's directory as the
 * cluster names them. A pronto outside that module is an installed one, whose
 * program_pronto.cue setup writes; an app declaring an installed pronto keeps
 * that layout whichever pronto writes it, as an app built in its own
 * repository does inside the monorepo. */
async function writeLayout(): Promise<void> {
  const real = (p: string | URL) => Deno.realPathSync(p).replaceAll("\\", "/").replace(/\/+$/, "");
  const app = real(appDir);
  const pronto = real(new URL(".", import.meta.url));
  let root = app;
  while (!(await exists(`${root}/cue.mod`))) {
    if (!root.includes("/", 1)) fail(`${appDir} is in no CUE module`);
    root = root.slice(0, root.lastIndexOf("/"));
  }
  if (!pronto.startsWith(`${root}/`)) return;
  const path = `${appDir}/program_pronto.cue`;
  const declared = await ifMissing(Deno.readTextFile(path), "");
  if (/^loop:\s*surface:\s*sources:\s*pronto:\s*""\s*$/m.test(declared)) return;
  const program = await Deno.readTextFile(`${appDir}/program.cue`);
  const named = pathFrom(app, pronto);
  if (!named.endsWith("plugins/pronto")) fail(`pronto at ${pronto} is not a runtime's plugins/pronto`);
  const pkg = program.match(/^package\s+(\w+)\s*$/m)?.[1] ?? fail(`${appDir}/program.cue declares no package`);
  // Only the loop's source pointer and the build dir: the cluster's root
  // and runtime derive from the cluster seat (`local`) and mecha's
  // defaults, so stating them here would fight the seat on every app whose
  // seat disagrees — which is every installed app.
  const text = [
    "// generated by pronto from the layout this app is built in — do not edit",
    "",
    `package ${pkg}`,
    "",
    `loop: surface: sources: pronto: ${JSON.stringify(named)}`,
    `build: meta: dir: ${JSON.stringify(app === root ? "" : app.slice(root.length + 1))}`,
    "",
  ].join("\n");
  if (declared !== text) await Deno.writeTextFile(path, text);
}

// Markup-derived declarations regenerate before the export that reads them —
// and once more after the write, because a component screen's html is itself
// an OUTPUT of the export (#Screen.markup) while derive reads the emitted
// screens. A run that moved one re-derives and re-exports once; a derivation
// still moving after that is a bug, never a longer loop.
await writeLayout();
await derive(appDir);
let written = await writeEmission(await exportEmission());
const settled = await derivedText();
await derive(appDir);
if ((await derivedText()) !== settled) {
  written = await writeEmission(await exportEmission());
  const again = await derivedText();
  await derive(appDir);
  if ((await derivedText()) !== again) fail("derivation did not settle in two passes");
}
console.error(`pronto write: ${written.length} files written → ${appDir}`);
