// Bundles a pronto app into a Cloudflare Worker + Durable Object release.
// The Worker serves static browser assets and routes /auth/*, /crud/*, and
// /electric/* to a Durable Object that runs the cluster over native SQLite.
//
//   deno run -A --config bundle/deno.json bundle/cloudflare.ts <appDir> --omnishell <dir> --mecha <dir> [--out <dir>]
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'

function fail(msg: string): never {
  console.error(`cloudflare: ${msg}`)
  Deno.exit(1)
}

const here = path.dirname(fileURLToPath(import.meta.url))
const args = Deno.args.slice()
const app = path.resolve(args.shift() ?? fail('usage: cloudflare.ts <appDir> --omnishell <dir> --mecha <dir> [--out <dir>]'))
const flags: Record<string, string> = {}
while (args.length) {
  const flag = args.shift()!
  flags[flag] = args.shift() ?? fail(`${flag} takes a value`)
}
const omnishell = path.resolve(flags['--omnishell'] ?? fail('--omnishell names the interpreter root'))
const mecha = path.resolve(flags['--mecha'] ?? fail('--mecha names the mecha root'))
const out = path.resolve(flags['--out'] ?? path.join(app, 'dist/cloudflare'))
for (const flag of Object.keys(flags)) {
  if (!['--omnishell', '--mecha', '--out'].includes(flag)) fail(`unknown flag ${flag}`)
}

const publicDir = path.join(out, 'public')
const srcDir = path.join(out, 'src')
await Deno.mkdir(publicDir, { recursive: true })
await Deno.mkdir(srcDir, { recursive: true })

// 1. Build the browser bundle without in-page cluster into <out>/public
const bundleScript = path.join(here, 'bundle.ts')
const bundleArgs = [
  'run', '-A', '--config', path.join(here, 'deno.json'),
  bundleScript, app,
  '--omnishell', omnishell,
  '--mecha', mecha,
  '--out', publicDir,
  '--no-cluster',
]
const bundleProc = new Deno.Command(Deno.execPath(), {
  args: bundleArgs,
  stdout: 'inherit',
  stderr: 'inherit',
}).outputSync()
if (!bundleProc.success) fail('bundle.ts failed')

// 2. Copy shell assets (such as opponent portraits) into <out>/public/shell/assets
const assetsDir = path.join(app, 'shell/assets')
try {
  const stat = await Deno.stat(assetsDir)
  if (stat.isDirectory) {
    const targetAssets = path.join(publicDir, 'shell/assets')
    await Deno.mkdir(targetAssets, { recursive: true })
    for await (const entry of Deno.readDir(assetsDir)) {
      if (entry.isFile) {
        await Deno.copyFile(path.join(assetsDir, entry.name), path.join(targetAssets, entry.name))
      }
    }
  }
} catch (err) {
  if (!(err instanceof Deno.errors.NotFound)) throw err
}

// 3. Read shell.json to extract tables and schema
const shellText = await Deno.readTextFile(path.join(app, 'shell/shell.json'))
const shell = JSON.parse(shellText) as {
  app?: string
  tables?: string[]
  schema?: Record<string, { fields?: Array<{ name: string; type: string; pk?: boolean }> }>
}
const appName = shell.app ?? path.basename(app)
const tables = shell.tables ?? []

function sqliteType(type: string): string {
  if (type === 'int' || type === 'integer') return 'INTEGER'
  if (type === 'boolean') return 'INTEGER'
  if (type === 'numeric' || type === 'real') return 'REAL'
  return 'TEXT'
}

const tableStatements: string[] = []
for (const table of tables) {
  const fields = shell.schema?.[table]?.fields ?? []
  if (fields.length > 0) {
    const cols = fields.map((f) => {
      let def = `"${f.name}" ${sqliteType(f.type)}`
      if (f.pk) def += ' PRIMARY KEY'
      return def
    })
    tableStatements.push(`CREATE TABLE IF NOT EXISTS "${table}" (\n  ${cols.join(',\n  ')}\n);`)
  } else {
    tableStatements.push(`CREATE TABLE IF NOT EXISTS "${table}" (id TEXT PRIMARY KEY, created_at TEXT);`)
  }
}
tableStatements.push(`CREATE TABLE IF NOT EXISTS "app_user" (id TEXT PRIMARY KEY, handle TEXT);`)

// 4. Emit src/index.ts (Cloudflare Worker + Durable Object cluster)
const workerTs = `// Generated by pronto for Cloudflare Workers + Durable Objects
import { DurableObject } from "cloudflare:workers";

interface ShapeEntry {
  offset: number;
  message: any;
}

export class ClusterDurableObject extends DurableObject {
  private tables: Set<string> = new Set(${JSON.stringify(tables)});
  private tail: number = 0;
  private entries: ShapeEntry[] = [];
  private waiters: Set<() => void> = new Set();
  private bootId: string = "cf-" + Math.random().toString(36).slice(2, 8);

  constructor(ctx: DurableObjectState, env: any) {
    super(ctx, env);
    this.initTables();
  }

  private initTables() {
    const sqlStatements = ${JSON.stringify(tableStatements)};
    for (const sql of sqlStatements) {
      this.ctx.storage.sql.exec(sql);
    }
  }

  private notifyWaiters() {
    for (const w of this.waiters) w();
    this.waiters.clear();
    const sockets = this.ctx.getWebSockets();
    for (const ws of sockets) {
      ws.send(JSON.stringify({ type: "poke", lsn: this.tail }));
    }
  }

  private recordChange(table: string, op: "insert" | "update" | "delete", row: Record<string, any>) {
    const offset = ++this.tail;
    const msg = {
      key: \`"public"."\${table}"/"\${row.id ?? ""}"\`,
      value: row,
      headers: {
        operation: op,
        relation: ["public", table],
        lsn: String(offset),
        op_position: 0,
        last: true
      }
    };
    this.entries.push({ offset, message: msg });
    if (this.entries.length > 1000) this.entries.shift();
    this.notifyWaiters();
  }

  async fetch(request: Request): Promise<Response> {
    const u = new URL(request.url);
    const path = u.pathname;

    // WebSocket upgrade
    if (request.headers.get("Upgrade") === "websocket") {
      const pair = new WebSocketPair();
      const [client, server] = Object.values(pair);
      this.ctx.acceptWebSocket(server);
      return new Response(null, { status: 101, webSocket: client });
    }

    // --- /auth/* ---
    if (request.method === "POST" && path === "/auth/guest") {
      const id = crypto.randomUUID();
      const user = { id, handle: \`truqueiro-\${id.slice(0, 4)}\`, guest: true };
      const token = btoa(JSON.stringify({ alg: "none", typ: "JWT" })) + "." +
                    btoa(JSON.stringify({ sub: id, role: "app_user", guest: true })) + ".";
      return Response.json({ token, user });
    }

    if (request.method === "POST" && path === "/auth/shape") {
      const body = await request.json().catch(() => ({})) as { table?: string };
      const table = body.table ?? "lobby";
      const token = btoa(JSON.stringify({ alg: "none", typ: "JWT" })) + "." +
                    btoa(JSON.stringify({ typ: "shape", table, where: "1=1" })) + ".";
      return Response.json({ token, table, where: "1=1", expires_in: 86400 });
    }

    if (request.method === "GET" && path === "/auth/whoami") {
      return Response.json({ id: "guest", handle: "guest", guest: true });
    }

    // --- /crud/v1/<table> ---
    if (path.startsWith("/crud/")) {
      const parts = path.split("/").filter(Boolean);
      const table = parts[parts.length - 1];
      if (!this.tables.has(table) && table !== "app_user") {
        return Response.json({ error: \`unknown table \${table}\` }, { status: 404 });
      }

      if (request.method === "GET") {
        let sql = \`SELECT * FROM "\${table}"\`;
        const params: any[] = [];
        const whereClauses: string[] = [];

        for (const [key, val] of u.searchParams) {
          if (key === "select" || key === "order" || key === "limit" || key === "offset") continue;
          if (val.startsWith("eq.")) {
            whereClauses.push(\`"\${key}" = ?\`);
            params.push(val.slice(3));
          }
        }

        if (whereClauses.length > 0) {
          sql += " WHERE " + whereClauses.join(" AND ");
        }

        const order = u.searchParams.get("order");
        if (order) {
          const [col, dir] = order.split(".");
          sql += \` ORDER BY "\${col}" \${dir?.toUpperCase() === "DESC" ? "DESC" : "ASC"}\`;
        }

        const limit = u.searchParams.get("limit");
        if (limit && /^\\d+$/.test(limit)) {
          sql += \` LIMIT \${limit}\`;
        }

        const rows = [...this.ctx.storage.sql.exec(sql, ...params)];
        return Response.json(rows);
      }

      if (request.method === "POST") {
        const body = await request.json();
        const items = Array.isArray(body) ? body : [body];
        for (const item of items) {
          const keys = Object.keys(item);
          const placeholders = keys.map(() => "?").join(", ");
          const cols = keys.map(k => \`"\${k}"\`).join(", ");
          const vals = keys.map(k => item[k]);
          this.ctx.storage.sql.exec(
            \`INSERT OR REPLACE INTO "\${table}" (\${cols}) VALUES (\${placeholders})\`,
            ...vals
          );
          this.recordChange(table, "insert", item);
        }
        return Response.json(items, { status: 201 });
      }

      if (request.method === "PATCH") {
        const body = await request.json();
        let targetId = "";
        for (const [key, val] of u.searchParams) {
          if (key === "id" && val.startsWith("eq.")) {
            targetId = val.slice(3);
          }
        }
        if (targetId) {
          const updates = Object.keys(body).map(k => \`"\${k}" = ?\`).join(", ");
          const vals = [...Object.values(body), targetId];
          this.ctx.storage.sql.exec(\`UPDATE "\${table}" SET \${updates} WHERE id = ?\`, ...vals);
          const updated = [...this.ctx.storage.sql.exec(\`SELECT * FROM "\${table}" WHERE id = ?\`, targetId)][0] ?? { id: targetId, ...body };
          this.recordChange(table, "update", updated);
          return Response.json(updated);
        }
        return Response.json({ ok: true });
      }

      if (request.method === "DELETE") {
        let targetId = "";
        for (const [key, val] of u.searchParams) {
          if (key === "id" && val.startsWith("eq.")) {
            targetId = val.slice(3);
          }
        }
        if (targetId) {
          this.ctx.storage.sql.exec(\`DELETE FROM "\${table}" WHERE id = ?\`, targetId);
          this.recordChange(table, "delete", { id: targetId });
        }
        return new Response(null, { status: 204 });
      }
    }

    // --- /electric/v1/shape ---
    if (path === "/electric/v1/shape") {
      const table = u.searchParams.get("table") || "lobby";
      const offset = u.searchParams.get("offset") || "-1";
      const live = u.searchParams.get("live") === "true";
      const handle = \`\${table}-\${this.bootId}\`;

      const headers: Record<string, string> = {
        "content-type": "application/json",
        "cache-control": "no-store",
        "electric-handle": handle,
        "electric-offset": \`\${this.tail}_0\`,
        "electric-up-to-date": "true"
      };

      if (offset === "-1") {
        let sql = \`SELECT * FROM "\${table}"\`;
        const order = u.searchParams.get("order");
        if (order) {
          const [col, dir] = order.split(".");
          sql += \` ORDER BY "\${col}" \${dir?.toUpperCase() === "DESC" ? "DESC" : "ASC"}\`;
        }
        const rows = [...this.ctx.storage.sql.exec(sql)];
        const msgs = rows.map((r: any) => ({
          key: \`"public"."\${table}"/"\${r.id ?? ""}"\`,
          value: r,
          headers: { operation: "insert", relation: ["public", table] }
        }));
        msgs.push({
          headers: { control: "up-to-date", global_last_seen_lsn: String(this.tail) }
        });
        return new Response(JSON.stringify(msgs), { headers });
      }

      const numOffset = parseInt(offset.split("_")[0], 10);
      const pending = this.entries.filter(e => e.offset > numOffset);

      if (pending.length > 0) {
        const msgs = pending.map(e => e.message);
        msgs.push({
          headers: { control: "up-to-date", global_last_seen_lsn: String(this.tail) }
        });
        return new Response(JSON.stringify(msgs), {
          headers: { ...headers, "electric-offset": \`\${this.tail}_0\` }
        });
      }

      if (live) {
        await new Promise<void>((resolve) => {
          const done = () => { clearTimeout(t); this.waiters.delete(done); resolve(); };
          const t = setTimeout(done, 15000);
          this.waiters.add(done);
        });

        const newPending = this.entries.filter(e => e.offset > numOffset);
        if (newPending.length > 0) {
          const msgs = newPending.map(e => e.message);
          msgs.push({
            headers: { control: "up-to-date", global_last_seen_lsn: String(this.tail) }
          });
          return new Response(JSON.stringify(msgs), {
            headers: { ...headers, "electric-offset": \`\${this.tail}_0\` }
          });
        }
        return new Response(null, { status: 204, headers });
      }

      return new Response(JSON.stringify([
        { headers: { control: "up-to-date", global_last_seen_lsn: String(this.tail) } }
      ]), { headers });
    }

    return Response.json({ error: "not found" }, { status: 404 });
  }
}

export default {
  async fetch(request: Request, env: any, ctx: ExecutionContext): Promise<Response> {
    const u = new URL(request.url);
    const path = u.pathname;

    // Route cluster endpoints to the shared singleton Durable Object
    if (
      path.startsWith("/auth/") ||
      path.startsWith("/crud/") ||
      path.startsWith("/electric/") ||
      path === "/ws"
    ) {
      const id = env.CLUSTER.idFromName("truco-cluster");
      const stub = env.CLUSTER.get(id);
      return stub.fetch(new Request("http://do.local" + u.pathname + u.search, request));
    }

    // Serve static client assets from the Assets binding
    if (env.ASSETS) {
      const res = await env.ASSETS.fetch(request);
      if (res.status === 404 && request.headers.get("accept")?.includes("text/html")) {
        // SPA fallback to index.html
        return env.ASSETS.fetch(new Request(new URL("/index.html", request.url), request));
      }
      return res;
    }

    return new Response("Not found", { status: 404 });
  }
};
`
await Deno.writeTextFile(path.join(srcDir, 'index.ts'), workerTs)

// 5. Emit wrangler.jsonc
const wranglerJsonc = `{
  "$schema": "node_modules/wrangler/config-schema.json",
  "name": "${appName}",
  "main": "src/index.ts",
  "compatibility_date": "2026-10-01",
  "compatibility_flags": ["nodejs_compat"],
  "assets": {
    "directory": "./public",
    "binding": "ASSETS",
    "not_found_handling": "single-page-application"
  },
  "durable_objects": {
    "bindings": [
      { "name": "CLUSTER", "class_name": "ClusterDurableObject" }
    ]
  },
  "migrations": [
    { "tag": "v1", "new_sqlite_classes": ["ClusterDurableObject"] }
  ]
}
`
await Deno.writeTextFile(path.join(out, 'wrangler.jsonc'), wranglerJsonc)

// 6. Emit package.json
const packageJson = `{
  "name": "${appName}-cloudflare",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "wrangler dev",
    "deploy": "wrangler deploy"
  },
  "devDependencies": {
    "@cloudflare/workers-types": "^4.20240925.0",
    "wrangler": "^3.80.0"
  }
}
`
await Deno.writeTextFile(path.join(out, 'package.json'), packageJson)
console.error(`cloudflare: ${out} ready with Worker, Durable Object cluster, and static assets`)
